version: "3.7"

services:

  #
  # Service definition for a consul-vault cluster.
  #
  # Docker DNS will consistently assume the host name of "consul-vault" for
  # this service definition.
  #
  # Instances use Docker DNS to find each other and bootstrap the cluster.
  #
  # CONSUL_VAULT_HOST_NAME can be used to set the host name to something other
  # than "consul-vault" for your production network.
  #
  # At least three instances are required for quorum unless IS_DEV is set.
  # 
  consul-vault:
    build: ..
    image: leoj3n/consul-vault:latest
    ports:
      - "8200"
      - "8500"
    environment:
      - CONSUL_DATACENTER_NAME=dc1
      - CONSUL_VAULT_HOST_NAME=consul-vault
