version: "3.7"

services:

  # Service definition for a consul-vault cluster.
  #
  # For local development:
  #   
  #   docker-compose --file local-compose.yml up --detach --scale ${service}=3
  #
  # The service uses the user-defined network and internal DNS for the host name
  # "consul-vault".
  #
  # Instances use the Docker DNS address of the service (passed in via the
  # SERVICE_HOST_NAME env var) to find each other and bootstrap the cluster.
  #
  # Note:
  #
  # Unless IS_DEV is set, at least three instances are required for quorum.
  consul-vault:
    build: ..
    image: leoj3n/consul-vault:latest
    ports:
      - "8200"
      - "8500"
    environment:
      - CONSUL_DATACENTER_NAME=dc1
      - SERVICE_HOST_NAME=consul-vault
